### ISSUE TITLE
Error on Generation

### ISSUE THREAD

**Issue by pryingopen3rdi** [SleeeepyZhou/sd-webui-GPT4V-Image-Captioner#6]
This happens everytime I try to use the captioner, and yes I have a valid API key in the field.

Thank you,

TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/components/image.py", line 197, in preprocess
    return image_utils.format_image(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/components/image.py", line 197, in preprocess
    return image_utils.format_image(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/components/image.py", line 197, in preprocess
    return image_utils.format_image(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/components/image.py", line 197, in preprocess
    return image_utils.format_image(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/components/image.py", line 197, in preprocess
    return image_utils.format_image(
  File "/mnt/AwfulIntel/StabilityMatrix/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/gradio/image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'

**Comment by SleeeepyZhou** [comment]
`gradio/queueing.py", line 536, in process_events`
`TypeError: save_pil_to_file() got an unexpected keyword argument 'name'`

Does it seem like there are many image processing errors here?

After checking, it seems that the error originated from a certain version of the Gradio library. The solution provided online is to downgrade the Gradio version to 3.31.0.

I hope it will be useful to you.
